### Python Pandas Working With HTML Tutorials- Part 4
In this Part we are going to learn about
<ol>
<li> read HTML(read_html)
<li> To HTML(to_html)

In [1]:
import pandas as pd

In [2]:
html=pd.read_html("https://en.wikipedia.org/wiki/Mobile_country_code")

In [3]:
type(html)

list

In [4]:
html

[   MCC  MNC Brand      Operator       Status Bands (MHz)  \
 0    1    1  TEST  Test network  Operational         any
 1    1    1  TEST  Test network  Operational         any
 2  999   99   NaN  Internal use  Operational         any
 3  999  999   NaN  Internal use  Operational         any

                               References and notes
 0                                              NaN
 1                                              NaN
 2  Internal use in private networks, no roaming[6]
 3  Internal use in private networks, no roaming[6]  ,
      Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB
 1                    412                                Afghanistan       AF
 2                    276                                    Albania       AL
 3                    603                                    Algeria       DZ
 4                    544  American Samoa (United States of America)       AS
 ..                   ...                                        ...      ...
 247                  452                                    Vietnam       VN
 248                  543                        W Wallis and Futuna       WF
 249                  421                                    Y Yemen       YE
 250                  645                                   Z Zambia       ZM
 251                  648                                   Zimbabwe       ZW

                                   Mobile network codes National MNC authority  \
 0             List of mobile network codes in Abkhazia                    NaN
 1          List of mobile network codes in Afghanistan                    NaN
 2              List of mobile network codes in Albania                    NaN
 3              List of mobile network codes in Algeria                    NaN
 4       List of mobile network codes in American Samoa                    NaN
 ..                                                 ...                    ...
 247        List of mobile network codes in the Vietnam                    NaN
 248  List of mobile network codes in Wallis and Futuna                    NaN
 249          List of mobile network codes in the Yemen                    NaN
 250             List of mobile network codes in Zambia                    NaN
 251           List of mobile network codes in Zimbabwe                    NaN

                       Remarks
 0    MCC is not listed by ITU
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ..                        ...
 247                       NaN
 248                       NaN
 249                       NaN
 250                       NaN
 251                       NaN

 [252 rows x 6 columns],
      MCC  MNC     Brand                  Operator           Status  \
 0    901    1       NaN                   Webbing          Unknown
 1    901    2       NaN            GlobalmatiX AG          Unknown
 2    901    3   Iridium                       NaN      Operational
 3    901    4       NaN  BBIX Singapore Pte. Ltd.          Unknown
 4    901    5       NaN      Thuraya RMSS Network      Operational
 ..   ...  ...       ...                       ...              ...
 99   902    1       NaN        MulteFire Alliance      Operational
 100  991    1       NaN    World's Global Telecom  Not operational
 101  991    2  5G Croco               Orange S.A.  Not operational
 102  991    3       NaN                 Halys SAS  Not operational
 103  991    4       NaN              E-Space Inc.          Unknown

     Bands (MHz)                               References and notes
 0          MVNO            Former ICO Satellite Management[51][52]
 1       Unknown  Former Sense Communications International; veh...
 2     Satellite                                                NaN
 3       Unknown                              Former Globalstar[54]
 4     Satellite                                                NaN
 ..          ...                                                ...
 99          LTE                                           [6][123]
 100     Unknown  temporarily assigned until 15 January 2021[102...
 101          5G  temporarily assigned until 6 August 2022[125][...
 102     Unknown  temporary assignment for trial until 5 April 2...
 103   Satellite  temporary assignment for trial until 17 Oct 20...

 [104 rows x 7 columns],
    MCC  MNC     Brand                 Operator       Status Bands (MHz)  \
 0  995    1  FonePlus  Sure (Diego Garcia) Ltd  Operational     GSM 900

                                 References and notes
 0  There appears to be no officially assigned MCC...  ,
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}html.skin-theme-clientpref-night .mw-parser-output .navbar li a abbr{color:var(--color-base)!important}@media(prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .navbar li a abbr{color:var(--color-base)!important}}@media print{.mw-parser-output .navbar{display:none!important}}vteTelecommunications  \
 0                                            History
 1                                           Pioneers
 2                                  Transmissionmedia
 3                      Network topologyand switching
 4                                       Multiplexing
 5                                           Concepts
 6                                   Types of network
 7                                   Notable networks
 8                                          Locations
 9  Telecommunication portal  Category  Outline  C...

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}html.skin-theme-clientpref-night .mw-parser-output .navbar li a abbr{color:var(--color-base)!important}@media(prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .navbar li a abbr{color:var(--color-base)!important}}@media print{.mw-parser-output .navbar{display:none!important}}vteTelecommunications.1
 0  Beacon Broadcasting Cable protection system Ca...
 1  Nasir Ahmed Edwin Howard Armstrong Mohamed M. ...
 2  Coaxial cable Fiber-optic communication optica...
 3  Bandwidth Links Nodes terminal Network switchi...
 4  Space-division Frequency-division Time-divisio...
 5  Communication protocol Computer network Data t...
 6  Cellular network Ethernet ISDN LAN Mobile NGN ...
 7  ARPANET BITNET CYCLADES FidoNet Internet Inter...
 8  Africa Americas North South Antarctica Asia Eu...
 9  Telecommunication portal  Category  Outline  C...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]

In [5]:
html[0]

,MCC,MNC,Brand,Operator,Status,Bands (MHz),References and notes
0,1,1,TEST,Test network,Operational,any,NaN
1,1,1,TEST,Test network,Operational,any,NaN
2,999,99,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"
3,999,999,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"

In [6]:
html[1]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [9]:
html= pd.read_html("https://en.wikipedia.org/wiki/Economy_of_the_United_States",match="Government debt")

In [11]:
html[1]

,Year,GDP (in Bil. US$PPP),GDP per capita (in US$ PPP),GDP (in Bil. US$nominal),GDP per capita (in US$ nominal),GDP growth (real),Inflation rate (in Percent),Unemployment (in Percent),Government debt (in % of GDP)
0,1980,2857.3,12552.9,2857.3,12552.9,-0.3%,13.5%,7.2%,NaN
1,1981,3207.0,13948.7,3207.0,13948.7,2.5%,10.4%,7.6%,NaN
2,1982,3343.8,14405.0,3343.8,14405.0,-1.8%,6.2%,9.7%,NaN
3,1983,3634.0,15513.7,3634.0,15513.7,4.6%,3.2%,9.6%,NaN
4,1984,4037.7,17086.4,4037.7,17086.4,7.2%,4.4%,7.5%,NaN
5,1985,4339.0,18199.3,4339.0,18199.3,4.2%,3.5%,7.2%,NaN
6,1986,4579.6,19034.8,4579.6,19034.8,3.5%,1.9%,7.0%,NaN
7,1987,4855.3,20001.0,4855.3,20001.0,3.5%,3.6%,6.2%,NaN
8,1988,5236.4,21376.0,5236.4,21376.0,4.2%,4.1%,5.5%,NaN
9,1989,5641.6,22814.1,5641.6,22814.1,3.7%,4.8%,5.3%,NaN
10,1990,5963.1,23848.0,5963.1,23848.0,1.9%,5.4%,5.6%,NaN
11,1991,6158.1,24302.8,6158.1,24302.8,-0.1%,4.2%,6.9%,NaN
12,1992,6520.3,25392.9,6520.3,25392.9,3.5%,3.0%,7.5%,NaN
13,1993,6858.6,26364.2,6858.6,26364.2,2.8%,3.0%,6.9%,NaN
14,1994,7287.3,27674.0,7287.3,27674.0,4.0%,2.6%,6.1%,NaN
15,1995,7639.8,28671.5,7639.8,28671.5,2.7%,2.8%,5.6%,NaN
16,1996,8073.1,29947.0,8073.1,29947.0,3.8%,2.9%,5.4%,NaN
17,1997,8577.6,31440.1,8577.6,31440.1,4.4%,2.3%,4.9%,NaN
18,1998,9062.8,32833.7,9062.8,32833.7,4.5%,1.5%,4.5%,NaN
19,1999,9631.2,34496.2,9631.2,34496.2,4.8%,2.2%,4.2%,NaN
20,2000,10251.0,36312.8,10251.0,36312.8,4.1%,3.4%,4.0%,NaN
21,2001,10581.9,37101.5,10581.9,37101.5,1.0%,2.8%,4.7%,53.1%
22,2002,10929.1,37945.8,10929.1,37945.8,1.7%,1.6%,5.8%,55.5%
23,2003,11456.5,39405.4,11456.5,39405.4,2.8%,2.3%,6.0%,58.6%
24,2004,12217.2,41641.6,12217.2,41641.6,3.9%,2.7%,5.5%,66.2%
25,2005,13039.2,44034.3,13039.2,44034.3,3.5%,3.4%,5.1%,65.5%
26,2006,13815.6,46216.9,13815.6,46216.9,2.8%,3.2%,4.6%,64.2%
27,2007,14474.3,47943.4,14474.3,47943.4,2.0%,2.9%,4.6%,64.6%
28,2008,14769.9,48470.6,14769.9,48470.6,0.1%,3.8%,5.8%,73.5%
29,2009,14478.1,47102.4,14478.1,47102.4,-2.6%,-0.3%,9.3%,86.7%
30,2010,15049.0,48586.3,15049.0,48586.3,2.7%,1.6%,9.6%,95.2%
31,2011,15599.7,50008.1,15599.7,50008.1,1.6%,3.1%,8.9%,99.5%
32,2012,16254.0,51736.7,16254.0,51736.7,2.3%,2.1%,8.1%,103.1%
33,2013,16880.6,53363.9,16880.6,53363.9,2.1%,1.5%,7.4%,104.3%
34,2014,17608.1,55263.8,17608.1,55263.8,2.5%,1.6%,6.1%,104.2%
35,2015,18295.0,57006.9,18295.0,57006.9,2.9%,0.1%,5.2%,104.6%
36,2016,18804.9,58179.6,18804.9,58179.6,1.8%,1.3%,4.9%,106.5%
37,2017,19612.1,60292.9,19612.1,60292.9,2.5%,2.1%,4.4%,105.5%
38,2018,20656.5,63165.2,20656.5,63165.2,3.0%,2.4%,3.9%,106.8%
39,2019,21539.9,65561.3,21539.9,65561.3,2.6%,1.8%,3.7%,108%
40,2020,21354.1,64461.6,21354.1,64461.6,-2.2%,1.2%,8.1%,131.8%
41,2021,23681.1,71257.9,23681.1,71257.9,6.1%,4.7%,5.4%,124.5%
42,2022,26006.9,77979.8,26006.9,77979.8,2.5%,8.0%,3.6%,118.6%
43,2023,27720.7,82715.1,27720.7,82715.1,2.9%,4.1%,3.6%,118.7%
44,2024,29167.7,86601.2,29167.7,86601.2,2.8%,2.9%,4.1%,121%
45,2025,30337.1,89677.8,30337.1,89677.8,2.2%,1.9%,4.4%,124.1%
46,2026,31526.9,92785.8,31526.9,92785.8,2.0%,2.1%,4.3%,126.6%
47,2027,32786.7,96070.1,32786.7,96070.1,2.1%,2.1%,4.2%,128.4%
48,2028,34096.0,99467.8,34096.0,99467.8,2.1%,2.1%,4.0%,130.2%
49,2029,35457.9,102987.0,35457.9,102987.0,2.1%,2.1%,4.0%,131.7%

In [12]:
html=pd.read_html("https://en.wikipedia.org/wiki/Minnesota",match="Average daily maximum and minimum temperatures for selected cities in Minnesota")

In [14]:
html[0]

              Location July (°F) July (°C) January (°F) January (°C)
0          Minneapolis     83/64     28/18         23/7       −4/−13
1           Saint Paul     83/63     28/17         23/6       −5/−14
2            Rochester     82/63     28/17         23/3       −5/−16
3               Duluth     76/55     24/13         19/1       −7/−17
4            St. Cloud     81/58     27/14        18/−1       −7/−18
5              Mankato     86/62     30/16         23/3       −5/−16
6  International Falls     77/52     25/11        15/−6       −9/−21

In [17]:
html[0].to_html('pt.html')